export const sekretariat = {
    building: "Sekretariat Kadin Indonesia",
    address:
      "Jl. H. R. Rasuna Said Blok X-5 No.Kav. 2-3, Kuningan, Jakarta  12950",
    // phone: ["(022) 4204028"],
    // phone: ["0812-9594-1990", "0822-8820-9900"],
    email: ["sekretariat@kadin.id"],
    facebook: "https://www.facebook.com/kadin.pusat/",
    twitter: "https://x.com/Kadin_Indonesia",
    youtube: "https://www.youtube.com/c/kadinindonesiaofficial",
    instagram: "https://www.instagram.com/kadin.indonesia.official/#",
    linkedin: "https://www.linkedin.com/company/kadin-indonesia-official/",
    logo: '/logo.png',
  };

  export const kabupatenKotaJabar = [
    "Kota Bogor",
    "Kota Sukabumi",
    "Kota Bandung",
    "Kota Cirebon",
    "Kota Bekasi",
    "Kota Depok",
    "Kota Cimahi",
    "Kota Tasikmalaya",
    "Kota Banjar",
    "Kabupaten Bogor",
    "Kabupaten Sukabumi",
    "Kabupaten Cianjur",
    "Kabupaten Bandung",
    "Kabupaten Garut",
    "Kabupaten Tasikmalaya",
    "Kabupaten Ciamis",
    "Kabupaten Kuningan",
    "Kabupaten Cirebon",
    "Kabupaten Majalengka",
    "Kabupaten Sumedang",
    "Kabupaten Indramayu",
    "Kabupaten Subang",
    "Kabupaten Purwakarta",
    "Kabupaten Karawang",
    "Kabupaten Bekasi",
    "Kabupaten Bandung Barat",
    "Kabupaten Pangandaran",
  ];